- name: conditions in ansible
  hosts: local
  connection: local
  vars_prompt:
    - name: number
      prompt: please enter a number
      

  tasks:
    - name: number is lessthan 100
      ansible.builtin.debug:
        msg: "the given number is Less than 100"
      when: number | int < 100

    - name: number is greaterthan 100
      ansible.builtin.debug:
        msg: " the given number is greaterthan 100"
      when: number | int > 100

