- name: conditions in ansible
  hosts: local
  connection: local
  vars:
    - promt: please enter a number
  tasks:
    - name: number is lessthan 100
      ansible.builtin.debug:
        msg: "the given number {{ number }} is Less than 100"
      when: number < 100
    - name: number is greaterthan 100
      ansible.builtin.debug:
        msg: " the given number {{ number }} is greaterthan 100"
      when: number > 100

