- name: Datatypes in ansible
  hosts: local
  connection: local
  vars:
    course: Devops
    duration: 23
    is_alive: true
    tools:
      - linux
      - ansible
      - shell
    concepts:
      ci: genkins
      concepts: "linux, shell"
  tasks:
    - name: printing course info
      ansible.builtin.debug:
        msg: "Hello, your course is: {{ course }}, Duration: {{ duration }}, is_alive?: {{ is_alive }}, Tools are: {{ tools }}, Concepts: {{ concepts }}"
