- name: functions
  hosts: local
  connection: local
  tasks:
      - name: default variable
        ansible.builtin.debug:
          msg: "{{ person | default('suresh') }}" #giving default value to perosn variable

    
      - name: making variable optional
        ansible.builtin.debug:
          msg: "{{ cat |  default('omit') }}" #making varible optional
      
      - name: ipaddress validation
        vars:
          ip: 400.600.659.458
        ansible.builtin.debug:
          msg: " The given ip address '{{ ip }}' is : {{ ip | ansible.utils.ipaddr }}"
          
        
      - name: ipadrress validation2
        vars:
          ipp: 125.46.8.8
        ansible.builtin.debug:
          msg: " The given ip address '{{ ipp }}' is : {{ ipp | ansible.utils.ipaddr }}"



      - name: transforming sting into list
        vars:
          fruits: "Apple,banana,kiwi,mango"
        ansible.builtin.debug:
          msg: " friuts are: {{ fruits | split(',') }} "

      - name: transforming map into list
        vars:
           fruits: {
             fruit1: apple
             fruit2: banana
             fruit3: kiwi
           }
        ansible.builtin.debug:
         msg: " fruits are: {{ fruits | dict2items }}"


    # - name: transforming list into map
    #   ansible.builtin.debug:
    #     fruits: [fruit1: apple, fruit2: banana, fruit3: kiwi]
    #     msg: " fruits are : {{ fruits | list2dict }}"
