- name: nginx installation
  hosts: frontend
  tasks:
    - name: nginx installation if it is redhat
      ansible.builtin.dnf:
        name: nginx
        state: present
        
      when: ansible_os_family == 'RedHat'
    
    - name: nginx installation if it is ubantu
      ansible.builtin.apt:
        name: nginx
        state: present
        
      when: ansible_os_family == 'Debian'