- name: variables
  hosts: local
  connection: local

  vars: 
    course: ansible
    duration: 10hr
    trainer: devi

  tasks:
    - name: print course information
      ansible.builtin.debug:
        msg: "Hello {{ course }}, course duration {{ duration }}, Trainer {{ trainer }}"
      
    - name: print course info again
      vars: 
        course: Devops
        duration: 6hr
        trainer: tarun
      ansible.builtin.debug:
        msg: "Hello {{ course }}, course duration {{ duration }}, Trainer {{ trainer }}"

